version: '3'
services:
  envs:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        V01a: v01
        V02a: v02
        V03a: v03
        V04a: v04
        V05a: v05
        V06a: v06
        V41a: v41
    container_name: printenv
    environment:
      V11a: 'v11'
      V12a: 'v12'
      V13a: 'v13'
      V14a: 'v14'
      V15a: 'v15'
      V16a: 'v16'
      V51a: 'v51'
      V61a: 'v61'
    volumes:
      - ./start.sh:/app/start.sh
